openapi: 3.0.0
info:
  title: Audio File Storage API
  description: API for storing and retrieving .mp3 audio files
  version: 1.0.0
servers:
- url: ""
  description: ""
paths:
  /audio:
    get:
      summary: Retrieve all uploaded audio files
      operationId: getAllAudioFiles
      responses:
        "200":
          description: A list of uploaded audio files
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/inline_response_200"
                x-content-type: application/json
      x-swagger-router-controller: Default
    post:
      summary: Upload an .mp3 audio file
      operationId: uploadAudio
      requestBody:
        content:
          audio/mpeg:
            schema:
              type: string
              format: binary
        required: true
      responses:
        "201":
          description: Audio file uploaded successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_201"
      x-swagger-router-controller: Default
  /audio/{fileName}:
    get:
      summary: Retrieve a specific .mp3 audio file
      operationId: getAudioFile
      parameters:
      - name: fileName
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: The requested audio file
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary
                x-content-type: audio/mpeg
        "404":
          description: Audio file not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_404"
      x-swagger-router-controller: Default
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        fileName:
          type: string
        fileUrl:
          type: string
      example:
        fileName: fileName
        fileUrl: fileUrl
    inline_response_201:
      type: object
      properties:
        message:
          type: string
          example: File uploaded successfully
      example:
        message: File uploaded successfully
    inline_response_404:
      type: object
      properties:
        message:
          type: string
          example: File not found
